snippets:
  - name: "Load Switchboard Program"
    description: ""
    filename: "load-program.ts"
  - name: "Create a Queue"
    description: ""
    filename: "create-queue.ts"
  - name: "Add an Oracle"
    description: ""
    filename: "add-an-oracle.ts"
  - name: "Create a Data Feed"
    description: ""
    filename: "create-a-data-feed.ts"
  - name: "Request a New Value"
    description: ""
    filename: "request-a-new-value.ts"
  - name: "Read a Data Feed"
    description: "After the oracles respond, read the feed result"
    filename: "read-data-feed.ts"
  - name: "Add a History Buffer"
    description:
      "Optionally, add a history buffer to your feed to store the last N
      historical samples"
    filename: "add-history-buffer.ts"
  - name: "Watch Data Feed"
    description:
      "Setup a websocket listener to invoke a callback whenever an aggregator is
      updated"
    filename: "watch-data-feed.ts"
