[package]
name = "spl-feed-parser"
version = "0.1.0"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
switchboard-aggregator = "0.1.6"
solana-program = "1.8.2"

[lib]
crate-type = ["cdylib", "lib"]
