snippets:
  - name: "Simulate an OracleJob"
    description: ""
    filename: "simulate-an-oracle-job.md"
  - name: "Create a Devnet Feed"
    description: ""
    filename: "create-devnet-feed.md"
  - name: "Create a Private Switchboard Network"
    description: ""
    filename: "create-private-network.md"
  - name: "Create a Feed with the CLI"
    description: ""
    filename: "create-a-feed-with-cli.md"
