[package]
name = "anchor-history-parser"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "anchor_history_parser"

[features]
default = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]

[profile.release]
overflow-checks = true

[dependencies]
switchboard-solana = { path = "../../rust/switchboard-solana" }
# switchboard-solana = { version = "^0.1" }
anchor-lang = "=0.26.0"
solana-program = "1.14.18"
