[package]
name = "switchboard-v2"
version = "0.1.23"
edition = "2021"
description = "A Rust library to interact with Switchboard V2 accounts."
readme = "README.md"
keywords = ["switchboard", "oracle", "solana"]
homepage = "https://docs.switchboard.xyz"
repository = "https://github.com/switchboard-xyz/sbv2-solana/tree/main/rust/switchboard-v2"
license = "MIT"
documentation = "https://docs.rs/switchboard-v2/"

[lib]
crate-type = ["cdylib", "lib"]
name = "switchboard_v2"
doctest = false

[features]
default = ["cpi"]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
rust_decimal = "=1.26.1"
bytemuck = "1.13.1"
superslice = "1"
solana-program = ">= 1.13.5, < 1.15.0"
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
# https://github.com/coral-xyz/anchor/issues/2502
# anchor-lang = { git = "https://github.com/coral-xyz/anchor", version = "0.27.0" }
# anchor-spl = { git = "https://github.com/coral-xyz/anchor", version = "0.27.0" }
toml_datetime = "=0.6.1"
winnow = "=0.4.1"
toml_edit = "=0.19.8"
